# Author: Lucian Adrian Grijincu (lucian.grijincu@gmail.com)
# Copyright (c) 2008 rosedu.org
# See LICENSE file for copyright and license details.

CFLAGS=-g -Wall

semctl: semctl.o

dist: semctl
	cp ./semctl ../bin/

clean:
	rm -f *~ semctl semctl.o
