CFLAGS = -Wall -g

all: hello_test

hello_test: hello_test.o

hello_test.o: hello_test.c test_lin.h

clean:
	-rm -f hello_test hello_test.o *~ *.zip

pre-build:

build: hello_test

post-build:

pre-run:

run: build
	./hello_test

post-run:

pack: hello_test.c test_lin.h Makefile.checker
	zip tests.zip hello_test.c test_lin.h Makefile.checker
